# News schemas
from app.news.schemas.article import (
    ArticleBase,
    ArticleCreate,
    ArticleUpdate,
    ArticleResponse,
    ArticleListResponse,
    ArticleStatsResponse,
    ArticleFilter,
)
from app.news.schemas.source import (
    SourceType,
    SourceBase,
    SourceCreate,
    SourceUpdate,
    SourceResponse,
    SourceTestResponse,
    SourceListResponse,
    SourceBatchDeleteRequest,
)
from app.news.schemas.user import (
    UserRole,
    OAuthProvider,
    UserBase,
    UserCreate,
    UserRegisterRequest,
    UserLoginRequest,
    UserUpdate,
    UserResponse,
    TokenResponse,
    TokenData,
    OAuthCallback,
)
from app.news.schemas.bookmark import (
    BookmarkBase,
    BookmarkCreate,
    BookmarkResponse,
    BookmarkWithArticle,
)
from app.news.schemas.strategy import (
    StrategyBase,
    StrategyCreate,
    StrategyUpdate,
    StrategyResponse,
    StrategyListResponse,
)
from app.news.schemas.monitor import (
    MonitorConfigCreate,
    MonitorConfigUpdate,
    MonitorConfigResponse,
)
from app.news.schemas.admin import (
    AdminStatsResponse,
    UserManagementResponse,
    UserRoleUpdate,
    SourceHealthResponse,
    QueueStatusResponse,
    SystemHealthResponse,
)
from app.news.schemas.paper import (
    PaperBase,
    PaperCreate,
    PaperResponse,
    PaperListResponse,
)

__all__ = [
    "ArticleBase",
    "ArticleCreate",
    "ArticleUpdate",
    "ArticleResponse",
    "ArticleListResponse",
    "ArticleStatsResponse",
    "ArticleFilter",
    "SourceType",
    "SourceBase",
    "SourceCreate",
    "SourceUpdate",
    "SourceResponse",
    "SourceTestResponse",
    "SourceListResponse",
    "SourceBatchDeleteRequest",
    "UserRole",
    "OAuthProvider",
    "UserBase",
    "UserCreate",
    "UserRegisterRequest",
    "UserLoginRequest",
    "UserUpdate",
    "UserResponse",
    "TokenResponse",
    "TokenData",
    "OAuthCallback",
    "BookmarkBase",
    "BookmarkCreate",
    "BookmarkResponse",
    "BookmarkWithArticle",
    "StrategyBase",
    "StrategyCreate",
    "StrategyUpdate",
    "StrategyResponse",
    "StrategyListResponse",
    "MonitorConfigCreate",
    "MonitorConfigUpdate",
    "MonitorConfigResponse",
    "AdminStatsResponse",
    "UserManagementResponse",
    "UserRoleUpdate",
    "SourceHealthResponse",
    "QueueStatusResponse",
    "SystemHealthResponse",
    "PaperBase",
    "PaperCreate",
    "PaperResponse",
    "PaperListResponse",
]
